name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    env:
      UV_PYTHON: "3.13"
      CUDA_VISIBLE_DEVICES: ""
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: astral-sh/setup-uv@v4
        with:
          version: latest
      - run: make ci
